Feat #25, #48 : 공유 게시판 전체 조회 (페이징) 및 상세 조회 API 구현
woo00oo/goGetterProjectServer pull request #49
Opened 2021-06-24 14:15 UTC by kimyubi

### **작업 사항**  
공유 게시판 전체 조회 (페이징) API 구현
공유 게시판 상세 조회 API 구현

### **작업 사항**    
최신순으로 정렬하여 한 페이지에 9개씩 조회  
공유 게시판 상세 조회

### 이슈 
#25 , #48

2021-06-24 15:26 UTC, JunyHarang requested changes
DTO들에 @Data가 있는데, @Data 안에는 @Setter가 포함되어 있어 사용 안하기로 했던거롤 기억하고 있는데, 사용하신 이유가 따로 있으실까요?

2021-06-24 17:24 UTC, kimyubi commented
> Question : DTO들에 @DaTa가 있는데, @DaTa 안에는 @Setter가 포함되어 있어 사용 안하기로 했던거롤 기억하고 있는데, 사용하신 이유가 따로 있으실까요?

modelMapper 내부에서 setter를 사용하는지 @Setter가 없으면 에러가 나더라고요 !

2021-06-25 14:56 UTC, woo00oo requested changes
N+1 문제 해결후에 다시 PR 부탁드려요

2021-06-26 13:29 UTC, kimyubi commented on src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardController.java
> +    @GetMapping(value = {"/api/user/sharings" ,"/api/bkuser/sharings"})
피드백 감사합니다! 말씀하신 부분 수정하여 다시 pr 보내도록 하겠습니다

2021-06-26 13:32 UTC, kimyubi commented on src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/BoardResponse.java
> +    private List<SharingBoardReply> sharingBoardReplyList = new LinkedList<>();
확인 했습니다 ! 피드백 감사합니다 ~

2021-06-26 17:44 UTC, closed without merging