feat #70 : 공유 게시판 좋아요 API 구현
woo00oo/goGetterProjectServer pull request #71
Opened 2021-06-27 00:16 UTC by kimyubi

[sharingBoard] 공유 게시판 API 구현

## 작업 사항
공유 게시판 좋아요 API 구현 

## 요약
게시글에 좋아요를 이미 누른 경우 좋아요 버튼을 누르면 좋아요 취소,
게시글에 좋아요가 눌러져 있지 않은 경우 좋아요 버튼을 누르면 좋아요 등록  

## 첨부
작업한 사진을 첨부할 경우 여기에 추가하세요.

## 이슈
issued : #70

2021-06-27 09:42 UTC, woo00oo approved these changes
Excellent : LGTM ! 빠르게 잘 구현하시네요 👍

2021-06-28 01:39 UTC, JunyHarang approved these changes

2021-06-28 01:50 UTC, JunyHarang requested changes
Essential : 코드 작성은 너무 좋다고 보이는데, 회의 때 얘기 했던 주석이 하나도 보이지 않습니다. 주석을 통해 변수, 메서드, 어노테이션 등이 무엇인지 남겨 주시면 좋겠습니다.

2021-06-28 02:19 UTC, JunyHarang requested changes
Question : SimpleBoardResponse라는 Class가 있는데, 보닌까 Shard Board에서 사용하는 DTO로 보이는데, ShardBoardResponse가 아니라 Simple로 이름 지으신 이유가 있으실까요?

2021-06-28 05:18 UTC, kimyubi commented
> Question : SimpleBoardResponse라는 Class가 있는데, 보닌까 Shard Board에서 사용하는 DTO로 보이는데, ShardBoardResponse가 아니라 Simple로 이름 지으신 이유가 있으실까요?

전체 게시글 목록 조회에서는 게시글 정보 전체를 조회 해오는 것이 아닌 일부 정보만 가져오기 때문에 
SimpleBoardResponse라고 네이밍했고 상세 조회에서는 BoardResponse라고 네이밍 했습니다 !

2021-06-28 11:10 UTC, closed without merging