#Feat 94: 공유 게시판 댓글 조회, 등록, 수정, 삭제 API 구현
woo00oo/goGetterProjectServer pull request #95
Opened 2021-07-01 20:37 UTC by kimyubi

### 작업 사항

#### 완료 목록

- 댓글 조회 API
- 댓글 등록 API
- 댓글 수정 API, 자신이 작성한 댓글이 아니면 수정 불가
- 댓글 삭제 API, 자신이 작성한 댓글이 아니면 삭제 불가

#### 진행 할 목록 (인기글 조회 까지 구현 후 리팩토링 예정)
- SharingBoard-SharingBoardReply 양방향 매핑을 단방향 매핑으로 리팩토링
- N+1 문제 체크 및 리팩토링
- 페이징 성능 개선
- JPQL 적용

### 첨부
- 댓글 조회  
![스크린샷(195)](https://user-images.githubusercontent.com/62657545/124185384-df1d1580-daf5-11eb-9f2d-f18b94a72019.png)

- 댓글 등록  
![스크린샷(196)](https://user-images.githubusercontent.com/62657545/124185499-08d63c80-daf6-11eb-988a-fc166f4713ef.png)

- 댓글 등록 후 조회  
![스크린샷(197)](https://user-images.githubusercontent.com/62657545/124185595-24d9de00-daf6-11eb-8231-b110b37e1107.png)

- 댓글 수정  
![스크린샷(201)](https://user-images.githubusercontent.com/62657545/124185980-9dd93580-daf6-11eb-818b-d8828fb8f11b.png)
![스크린샷(202)](https://user-images.githubusercontent.com/62657545/124186011-a7fb3400-daf6-11eb-9d8a-ec610261bbb3.png)

- 댓글 수정 ( 사용자 아이디가 작성자의 아이디와 다른 경우)  
![스크린샷(206)](https://user-images.githubusercontent.com/62657545/124186140-d842d280-daf6-11eb-8f5e-bbc87a9efcb1.png)

- 댓글 삭제 ( 사용자 아이디가 작성자의 아이디와 일치하는 경우)  
![스크린샷(210)](https://user-images.githubusercontent.com/62657545/124186361-2e177a80-daf7-11eb-93a8-05a6bac0114b.png)

-댓글 삭제 (사용자 아이디가 작성자 아이디와 다른 경우)
![스크린샷(209)](https://user-images.githubusercontent.com/62657545/124186428-45566800-daf7-11eb-8052-3543b74b1659.png)

댓글 수정, 삭제, 등록 후 조회 테스트도 수행하였으나 비슷한 사진이 너무 많아져 사진 첨부 생략

### 이슈

- issued : #94

2021-07-02 00:31 UTC, woo00oo approved these changes
Excellent : 고생하셨습니다 👍

2021-07-02 02:08 UTC, torvlf approved these changes
Excellent: 고생하셨습니다.

2021-07-03 14:34 UTC, JunyHarang approved these changes
Excellent : 고생하셨습니다!

2021-07-05 02:04 UTC, JunyHarang requested changes
Question : RestAPI 설계 단계에서 공유 게시판 글 수정 API에 URI를 '/api/user/sharings/{id}' 이렇게 설계하기로 작성 하셨는데, 실제 코딩에서는 '/api/user/sharings' 이렇게 작성이 되어 있습니다
이렇게 하신 이유가 있을까요?

2021-07-06 05:18 UTC, merged